# Generated by Django 5.2.4 on 2025-08-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DalyWork", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dalyworkpost",
            name="client",
            field=models.TextField(),
        ),
    ]
