# Generated by Django 5.2.5 on 2025-08-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EconomicT", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="economictpost",
            name="banner0",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AddField(
            model_name="economictpost",
            name="banner2",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AddField(
            model_name="economictpost",
            name="banner3",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AddField(
            model_name="economictpost",
            name="banner4",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AddField(
            model_name="economictpost",
            name="banner5",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AddField(
            model_name="economictpost",
            name="banner6",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AddField(
            model_name="economictpost",
            name="banner7",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AddField(
            model_name="economictpost",
            name="banner8",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AddField(
            model_name="economictpost",
            name="banner9",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
    ]
