# Generated by Django 5.2.5 on 2025-08-11 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EconomicT", "0002_economictpost_banner0_economictpost_banner2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="economictpost",
            old_name="banner0",
            new_name="banner1",
        ),
    ]
