# Generated by Django 5.2.4 on 2025-08-12 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EconomicT", "0003_rename_banner0_economictpost_banner1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="economictpost",
            old_name="banner1",
            new_name="aanner1",
        ),
        migrations.RemoveField(
            model_name="economictpost",
            name="banner2",
        ),
        migrations.RemoveField(
            model_name="economictpost",
            name="banner3",
        ),
        migrations.RemoveField(
            model_name="economictpost",
            name="banner4",
        ),
        migrations.RemoveField(
            model_name="economictpost",
            name="banner5",
        ),
        migrations.RemoveField(
            model_name="economictpost",
            name="banner6",
        ),
        migrations.RemoveField(
            model_name="economictpost",
            name="banner7",
        ),
        migrations.RemoveField(
            model_name="economictpost",
            name="banner8",
        ),
        migrations.RemoveField(
            model_name="economictpost",
            name="banner9",
        ),
    ]
