# Generated by Django 5.2.4 on 2025-08-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EconomicT", "0004_rename_banner1_economictpost_aanner1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="economictpost",
            old_name="aanner1",
            new_name="AA",
        ),
        migrations.RenameField(
            model_name="economictpost",
            old_name="banner",
            new_name="BB",
        ),
        migrations.AddField(
            model_name="economictpost",
            name="CC",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AddField(
            model_name="economictpost",
            name="DD",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
    ]
