# Generated by Django 5.2.4 on 2025-08-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EconomicT", "0005_rename_aanner1_economictpost_aa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="economictpost",
            name="EE",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AddField(
            model_name="economictpost",
            name="FF",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
    ]
