# Generated by Django 5.2.4 on 2025-08-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ChangJiangE", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="changjiangepost",
            old_name="banner",
            new_name="AA",
        ),
        migrations.AddField(
            model_name="changjiangepost",
            name="BB",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AddField(
            model_name="changjiangepost",
            name="CC",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AddField(
            model_name="changjiangepost",
            name="DD",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AddField(
            model_name="changjiangepost",
            name="EE",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AddField(
            model_name="changjiangepost",
            name="FF",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AlterField(
            model_name="changjiangepost",
            name="client",
            field=models.TextField(),
        ),
    ]
