# Generated by Django 5.1.7 on 2025-05-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FirstApp", "0002_post_banner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
    ]
