# Generated by Django 5.2.4 on 2025-08-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FirstApp", "0003_remove_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="client",
            field=models.TextField(),
        ),
    ]
