# Generated by Django 5.2.4 on 2025-08-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FirstApp", "0004_alter_post_client"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="banner",
            new_name="AA",
        ),
        migrations.AddField(
            model_name="post",
            name="BB",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AddField(
            model_name="post",
            name="CC",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AddField(
            model_name="post",
            name="DD",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AddField(
            model_name="post",
            name="EE",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AddField(
            model_name="post",
            name="FF",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
    ]
