# Generated by Django 5.2.4 on 2025-08-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ShunFeng", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shunfengpost",
            name="client",
            field=models.TextField(),
        ),
    ]
